version: '2'

services:
  database:
    image: mysql:5.7
    volumes:
      - database-content:/var/lib/mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: "baton"
      MYSQL_USER: "baton"
      MYSQL_PASSWORD: "baton"
      MYSQL_ROOT_PASSWORD: "baton"

  baton:
    build: "docker/container/baton"
    command: "dockerize -wait tcp://database:3306 bash -c 'composer install && php -v'"
    volumes:
      - .:/usr/app/baton
    restart: on-failure
    depends_on:
      - database
    ports:
      - "8080:8080"

volumes:
  database-content:
